version: "3"
services:
  tsc:
    build: .
    volumes:
      - .:/home/node/code
      - /home/node/code/node_modules
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html/